# Documentation https://golangci-lint.run/usage/linters

issues:
  new: true
  fix: true
  new-from-rev: 1de9aaed0441349ba34f1d3cfb18cc2b36114bc5

run:
  timeout: 10m
  issues-exit-code: 1
  tests: false
  skip-dirs-use-default: true

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    #- dupl
    - errcheck
    - errname
    - exhaustive
    - exportloopref
    - goconst
    - gocritic #TODO: https://go-critic.com/overview.html
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - predeclared
    - staticcheck
    - tagliatelle # remove this for existing projects
    - typecheck
    - unconvert
    - unused
    - whitespace
    - wsl

linters-settings:
  gocyclo:
    min-complexity: 20
  goimports:
    local-prefixes: github.com/RocketChat/airlock
  gomnd:
    ignored-functions:
      - "utils.Generate*"
      - "core.AddMigration"
  misspell:
    locale: US
  nlreturn:
    block-size: 2
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: camel
        yaml: camel
        bson: camel
  wsl:
    allow-assign-and-call: false
    allow-multiline-assign: false
    force-err-cuddling: true
