# permissions for end users to edit mongodbaccessrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mongodbaccessrequest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: airlock
    app.kubernetes.io/part-of: airlock
    app.kubernetes.io/managed-by: kustomize
  name: mongodbaccessrequest-editor-role
rules:
- apiGroups:
  - airlock.cloud.rocket.chat
  resources:
  - mongodbaccessrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - airlock.cloud.rocket.chat
  resources:
  - mongodbaccessrequests/status
  verbs:
  - get
