---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resourceNames:
  - '*'
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - apps
  - networking.k8s.io
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - airlock.cloud.rocket.chat
  resources:
  - mongodbaccessrequests
  - mongodbbackups
  - mongodbbackupschedules
  - mongodbbackupstores
  - mongodbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - airlock.cloud.rocket.chat
  resources:
  - mongodbaccessrequests/finalizers
  - mongodbbackups/finalizers
  - mongodbbackupschedules/finalizers
  - mongodbbackupstores/finalizers
  - mongodbclusters/finalizers
  verbs:
  - update
- apiGroups:
  - airlock.cloud.rocket.chat
  resources:
  - mongodbaccessrequests/status
  - mongodbbackups/status
  - mongodbbackupschedules/status
  - mongodbbackupstores/status
  - mongodbclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - airlock.cloud.rocket.chat
  resources:
  - mongodbbackupstorestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
