apiVersion: airlock.cloud.rocket.chat/v1alpha1
kind: MongoDBCluster
metadata:
  labels:
    app.kubernetes.io/name: mongodbcluster
    app.kubernetes.io/instance: mongodbcluster-sample
    app.kubernetes.io/part-of: airlock
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: airlock
  name: mongodbcluster-sample
spec:
  clusterName: teste
  connectionString: "mongo://meumonguinho/umsetdereplicas"
