apiVersion: airlock.cloud.rocket.chat/v1alpha1
kind: MongoDBCluster
metadata:
  name: teste-mongodb1
spec:
  connectionString: "mongodb://rcadmin:pamonha@mongodb.airlock-test/admin?replicaSet=rs0"
  hostTemplate: "mongodb.airlock-test"
  optionsTemplate: ?replicaSet=rs0