## Append samples you want in your CSV to this file as resources ##
resources:
- airlock_v1alpha1_mongodbcluster.yaml
- airlock_v1alpha1_mongodbaccessrequest.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
