//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtlasScheduledAutoscaling) DeepCopyInto(out *AtlasScheduledAutoscaling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtlasScheduledAutoscaling.
func (in *AtlasScheduledAutoscaling) DeepCopy() *AtlasScheduledAutoscaling {
	if in == nil {
		return nil
	}
	out := new(AtlasScheduledAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAccessRequest) DeepCopyInto(out *MongoDBAccessRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAccessRequest.
func (in *MongoDBAccessRequest) DeepCopy() *MongoDBAccessRequest {
	if in == nil {
		return nil
	}
	out := new(MongoDBAccessRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBAccessRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAccessRequestList) DeepCopyInto(out *MongoDBAccessRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MongoDBAccessRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAccessRequestList.
func (in *MongoDBAccessRequestList) DeepCopy() *MongoDBAccessRequestList {
	if in == nil {
		return nil
	}
	out := new(MongoDBAccessRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBAccessRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAccessRequestSpec) DeepCopyInto(out *MongoDBAccessRequestSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAccessRequestSpec.
func (in *MongoDBAccessRequestSpec) DeepCopy() *MongoDBAccessRequestSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBAccessRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAccessRequestStatus) DeepCopyInto(out *MongoDBAccessRequestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAccessRequestStatus.
func (in *MongoDBAccessRequestStatus) DeepCopy() *MongoDBAccessRequestStatus {
	if in == nil {
		return nil
	}
	out := new(MongoDBAccessRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackup) DeepCopyInto(out *MongoDBBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackup.
func (in *MongoDBBackup) DeepCopy() *MongoDBBackup {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackupList) DeepCopyInto(out *MongoDBBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MongoDBBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackupList.
func (in *MongoDBBackupList) DeepCopy() *MongoDBBackupList {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackupSchedule) DeepCopyInto(out *MongoDBBackupSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackupSchedule.
func (in *MongoDBBackupSchedule) DeepCopy() *MongoDBBackupSchedule {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackupSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBBackupSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackupScheduleList) DeepCopyInto(out *MongoDBBackupScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MongoDBBackupSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackupScheduleList.
func (in *MongoDBBackupScheduleList) DeepCopy() *MongoDBBackupScheduleList {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackupScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBBackupScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackupScheduleSpec) DeepCopyInto(out *MongoDBBackupScheduleSpec) {
	*out = *in
	in.BackupSpec.DeepCopyInto(&out.BackupSpec)
	if in.SuccessfulJobsHistoryLimit != nil {
		in, out := &in.SuccessfulJobsHistoryLimit, &out.SuccessfulJobsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.FailedJobsHistoryLimit != nil {
		in, out := &in.FailedJobsHistoryLimit, &out.FailedJobsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackupScheduleSpec.
func (in *MongoDBBackupScheduleSpec) DeepCopy() *MongoDBBackupScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackupScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackupScheduleStatus) DeepCopyInto(out *MongoDBBackupScheduleStatus) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.LastBackupTime != nil {
		in, out := &in.LastBackupTime, &out.LastBackupTime
		*out = (*in).DeepCopy()
	}
	if in.LastFailureTime != nil {
		in, out := &in.LastFailureTime, &out.LastFailureTime
		*out = (*in).DeepCopy()
	}
	if in.ActiveBackups != nil {
		in, out := &in.ActiveBackups, &out.ActiveBackups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackupScheduleStatus.
func (in *MongoDBBackupScheduleStatus) DeepCopy() *MongoDBBackupScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackupScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackupSpec) DeepCopyInto(out *MongoDBBackupSpec) {
	*out = *in
	if in.ExcludedCollections != nil {
		in, out := &in.ExcludedCollections, &out.ExcludedCollections
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludedCollections != nil {
		in, out := &in.IncludedCollections, &out.IncludedCollections
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.BackupStoreRef = in.BackupStoreRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackupSpec.
func (in *MongoDBBackupSpec) DeepCopy() *MongoDBBackupSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackupStatus) DeepCopyInto(out *MongoDBBackupStatus) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Result != nil {
		in, out := &in.Result, &out.Result
		*out = new(MongoDBBackupStatusResult)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackupStatus.
func (in *MongoDBBackupStatus) DeepCopy() *MongoDBBackupStatus {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackupStatusJob) DeepCopyInto(out *MongoDBBackupStatusJob) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackupStatusJob.
func (in *MongoDBBackupStatusJob) DeepCopy() *MongoDBBackupStatusJob {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackupStatusJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackupStatusResult) DeepCopyInto(out *MongoDBBackupStatusResult) {
	*out = *in
	if in.Job != nil {
		in, out := &in.Job, &out.Job
		*out = new(MongoDBBackupStatusJob)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackupStatusResult.
func (in *MongoDBBackupStatusResult) DeepCopy() *MongoDBBackupStatusResult {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackupStatusResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackupStore) DeepCopyInto(out *MongoDBBackupStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackupStore.
func (in *MongoDBBackupStore) DeepCopy() *MongoDBBackupStore {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackupStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBBackupStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackupStoreList) DeepCopyInto(out *MongoDBBackupStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MongoDBBackupStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackupStoreList.
func (in *MongoDBBackupStoreList) DeepCopy() *MongoDBBackupStoreList {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackupStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBBackupStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackupStoreRef) DeepCopyInto(out *MongoDBBackupStoreRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackupStoreRef.
func (in *MongoDBBackupStoreRef) DeepCopy() *MongoDBBackupStoreRef {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackupStoreRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackupStoreS3) DeepCopyInto(out *MongoDBBackupStoreS3) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackupStoreS3.
func (in *MongoDBBackupStoreS3) DeepCopy() *MongoDBBackupStoreS3 {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackupStoreS3)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackupStoreSpec) DeepCopyInto(out *MongoDBBackupStoreSpec) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(MongoDBBackupStoreS3)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackupStoreSpec.
func (in *MongoDBBackupStoreSpec) DeepCopy() *MongoDBBackupStoreSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackupStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBBackupStoreStatus) DeepCopyInto(out *MongoDBBackupStoreStatus) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBBackupStoreStatus.
func (in *MongoDBBackupStoreStatus) DeepCopy() *MongoDBBackupStoreStatus {
	if in == nil {
		return nil
	}
	out := new(MongoDBBackupStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBCluster) DeepCopyInto(out *MongoDBCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBCluster.
func (in *MongoDBCluster) DeepCopy() *MongoDBCluster {
	if in == nil {
		return nil
	}
	out := new(MongoDBCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBClusterList) DeepCopyInto(out *MongoDBClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MongoDBCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBClusterList.
func (in *MongoDBClusterList) DeepCopy() *MongoDBClusterList {
	if in == nil {
		return nil
	}
	out := new(MongoDBClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBClusterSpec) DeepCopyInto(out *MongoDBClusterSpec) {
	*out = *in
	if in.AtlasScheduledAutoscaling != nil {
		in, out := &in.AtlasScheduledAutoscaling, &out.AtlasScheduledAutoscaling
		*out = new(AtlasScheduledAutoscaling)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBClusterSpec.
func (in *MongoDBClusterSpec) DeepCopy() *MongoDBClusterSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBClusterStatus) DeepCopyInto(out *MongoDBClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBClusterStatus.
func (in *MongoDBClusterStatus) DeepCopy() *MongoDBClusterStatus {
	if in == nil {
		return nil
	}
	out := new(MongoDBClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3SecretMappings) DeepCopyInto(out *S3SecretMappings) {
	*out = *in
	out.AccessKeyID = in.AccessKeyID
	out.SecretAccessKey = in.SecretAccessKey
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3SecretMappings.
func (in *S3SecretMappings) DeepCopy() *S3SecretMappings {
	if in == nil {
		return nil
	}
	out := new(S3SecretMappings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3SecretRef) DeepCopyInto(out *S3SecretRef) {
	*out = *in
	out.Mappings = in.Mappings
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3SecretRef.
func (in *S3SecretRef) DeepCopy() *S3SecretRef {
	if in == nil {
		return nil
	}
	out := new(S3SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToKeyMap) DeepCopyInto(out *ToKeyMap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToKeyMap.
func (in *ToKeyMap) DeepCopy() *ToKeyMap {
	if in == nil {
		return nil
	}
	out := new(ToKeyMap)
	in.DeepCopyInto(out)
	return out
}
