name: Build and Test
on:
  push:
    tags:
      - v*
    branches:
      - develop
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
env:
  __W_SRC_REL: go/src/github.com/RocketChat/airlock
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ${{ env.__W_SRC_REL }}
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
          cache: false
      - name: Build binary
        run: |
          cd $__W_SRC_REL
          go mod tidy
          make build
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERREGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERREGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.__W_SRC_REL }}
          file: ${{ env.__W_SRC_REL }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            rocketchat/airlock:${{github.sha}}

