name: Build and Test
on:
  push:
    tags:
      - v*
    branches:
      - develop
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
env:
  __W_SRC_REL: go/src/github.com/RocketChat/airlock
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    #services:
    # none currently

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ${{ env.__W_SRC_REL }}
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: dockerhub.com
          username: ${{ secrets.DOCKERREGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERREGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          secrets: |
            PRIVATE_REPO_ACCESS_KEY=${{ secrets.PRIVATE_REPO_ACCESS_KEY }}
            GOPRIVATE=github.com/RocketChat

          tags: |
            dockerhub.com/airlock:${{github.sha}}
