name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - develop
      - master
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Configure git for private modules
        env:
          PRIVATE_REPO_ACCESS_KEY: ${{ secrets.PRIVATE_REPO_ACCESS_KEY }}
        run: git config --global url."https://rocketchat-cloudbot:$PRIVATE_REPO_ACCESS_KEY@github.com".insteadOf "https://github.com"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48
          skip-build-cache: true
          only-new-issues: true

